set nocp ai si noet ts=4 sw=4 sta sm nu ru rnu mouse=a
set tf lz hls is ls=2 ch=2 list lcs=tab:>\ ,trail:. t_Co=256 spell
colo molokai
syn on
imap {<CR> {<CR>}<Esc>O





" nocp		nocompatible (helps fix things)
" ai		autoindent
" si		smartindent
" noet		noexpandtab (don't make tabs into spaces)
" ts=4		tabstop (number of spaces that a tab counts for)
" sw=4		shiftwidth (equivalent number of spaces per indent)
" sta		smarttab
" sm		showmatch
" nu		numbering
" ru		ruler
" rnu		relativenumber
" mouse=a	(click with mouse)
" tf		ttyfast (optimization)
" lz		lazyredraw (optimization)
" confirm	(before quit)####################### Not in use
" hls		hlsearch (highlight)
" is		incsearch
" ls=2		laststatus
" ch=2		cmdheight (cmdbar height)
" list		allow formatting of tabs/trailing space
" lsc		listchars (replace with)
" syn		syntax on
